<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Cotton Slim-Fit Chino Gabardine Pant for Men - Khaki - NZ-3176',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '71',
                'thumbnail_img' => '71',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 1520.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 1,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 0,
                'seller_featured' => 0,
                'current_stock' => 10,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'amount',
                'discount_start_date' => 1658880000,
                'discount_end_date' => 1659743940,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Cotton Printed Panjabi for Men - AshCotton Slim-Fit Chino Gabardine Pant for Men - Khaki - NZ-3176',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '71',
                'pdf' => NULL,
                'slug' => 'cotton-slim-fit-chino-gabardine-pant-for-men-khaki-nz-3176',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:04:46',
                'updated_at' => '2022-07-27 05:44:23',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Cotton Printed Panjabi for Men - Ash - 17638P',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '56,57,54,55,53',
                'thumbnail_img' => '56',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 1520.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 0,
                'published' => 0,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 1,
                'seller_featured' => 0,
                'current_stock' => 0,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'percent',
                'discount_start_date' => 1653609600,
                'discount_end_date' => 1656374340,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Cotton Printed Panjabi for Men - Ash',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '56',
                'pdf' => NULL,
                'slug' => 'cotton-printed-panjabi-for-men-ash-17638p-c4neV',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:05:57',
                'updated_at' => '2022-05-25 19:23:29',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Cotton Printed Panjabi for Men - Ash - 17638P',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '56,57,54,55,53',
                'thumbnail_img' => '56',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 1520.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 0,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 0,
                'seller_featured' => 0,
                'current_stock' => 0,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'percent',
                'discount_start_date' => 1653609600,
                'discount_end_date' => 1656374340,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Cotton Printed Panjabi for Men - Ash',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '56',
                'pdf' => NULL,
                'slug' => 'cotton-printed-panjabi-for-men-ash-17638p-c4neV-GCbyp',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:10:44',
                'updated_at' => '2022-05-25 19:23:56',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Digital Printed Silk Saree for Women - Multicolor - MSS-7',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 10,
                'brand_id' => 1,
                'photos' => '75',
                'thumbnail_img' => '75',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 5004.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC","#DC143C"]',
                'variations' => NULL,
                'todays_deal' => 1,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 1,
                'seller_featured' => 0,
                'current_stock' => 10,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'amount',
                'discount_start_date' => 1659744000,
                'discount_end_date' => 1661039940,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Digital Printed Silk Saree for Women - Multicolor - MSS-7',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '75',
                'pdf' => NULL,
                'slug' => 'digital-printed-silk-saree-for-women-multicolor-mss-7',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:10:50',
                'updated_at' => '2022-08-06 15:38:36',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Digital Printed Silk Saree for Women - Multicolor - MSS-4',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 10,
                'brand_id' => 1,
                'photos' => '76',
                'thumbnail_img' => '76',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 5000.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 1,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 1,
                'seller_featured' => 0,
                'current_stock' => 10,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'amount',
                'discount_start_date' => 1659744000,
                'discount_end_date' => 1661039940,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Digital Printed Silk Saree for Women - Multicolor - MSS-4',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '76',
                'pdf' => NULL,
                'slug' => 'digital-printed-silk-saree-for-women-multicolor-mss-4',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:10:54',
                'updated_at' => '2022-08-06 15:38:36',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Twill Cotton Mobile-Cargo Pant for Men - Navy Blue',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '74',
                'thumbnail_img' => '74',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 500.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 0,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 1,
                'seller_featured' => 0,
                'current_stock' => 10,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'percent',
                'discount_start_date' => 1653609600,
                'discount_end_date' => 1656374340,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Twill Cotton Mobile-Cargo Pant for Men - Navy Blue',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '74',
                'pdf' => NULL,
                'slug' => 'twill-cotton-mobile-cargo-pant-for-men-navy-blue',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:10:57',
                'updated_at' => '2022-05-25 19:23:25',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Twill Cotton Stretchable Gabardine Pant for Men - Khaki',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '73',
                'thumbnail_img' => '73',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 1520.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#00FFFF","#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 1,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 1,
                'seller_featured' => 0,
                'current_stock' => 10,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'amount',
                'discount_start_date' => 1658880000,
                'discount_end_date' => 1659743940,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Twill Cotton Stretchable Gabardine Pant for Men - Khaki',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '73',
                'pdf' => NULL,
                'slug' => 'twill-cotton-stretchable-gabardine-pant-for-men-khaki',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:11:01',
                'updated_at' => '2022-07-27 05:44:23',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Cotton Printed Panjabi for Men - Ash - 17638P',
                'added_by' => 'admin',
                'user_id' => 9,
                'category_id' => 9,
                'brand_id' => 1,
                'photos' => '56,57,54,55,53',
                'thumbnail_img' => '56',
                'video_provider' => 'youtube',
                'video_link' => 'https://www.youtube.com/watch?v=ObajPJazNo8',
                'tags' => 'shirt,pant,panjabi',
            'description' => '<p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Cotton Printed Panjabi for Men</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>Product Type: Panjabi</li><li>Material: Cotton</li><li>Style: Casual</li><li>Country of Origin: Bangladesh</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><span style="font-weight: bolder;">Men\'s Size: 38, 40, 42, 44</span></p><ul style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><li>38: Chest 40, Length 38</li><li>40: Chest: 42, Length 40</li><li>42: Chest 44, Length 42</li><li>44: Chest 46, Length 44</li></ul><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><p><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"><br style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px;"></p><h6 class="mr-3 lh-1-8" style="color: rgb(27, 27, 40); font-family: &quot;Open Sans&quot;, sans-serif;"><span class="text text-primary mr-2 "><span style="font-weight: bolder;">Disclaimer:</span></span>The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.</h6>',
                'unit_price' => 1520.0,
                'purchase_price' => NULL,
                'variant_product' => 1,
                'attributes' => '[]',
                'choice_options' => '[]',
                'colors' => '["#F5F5DC"]',
                'variations' => NULL,
                'todays_deal' => 1,
                'published' => 1,
                'approved' => 1,
                'stock_visibility_state' => 'quantity',
                'cash_on_delivery' => 1,
                'featured' => 0,
                'seller_featured' => 0,
                'current_stock' => 0,
                'unit' => '50',
                'min_qty' => 1,
                'low_stock_quantity' => 1,
                'discount' => 20.0,
                'discount_type' => 'amount',
                'discount_start_date' => 1659744000,
                'discount_end_date' => 1661039940,
                'tax' => NULL,
                'tax_type' => NULL,
                'shipping_type' => 'free',
                'shipping_cost' => 0.0,
                'is_quantity_multiplied' => 0,
                'est_shipping_days' => NULL,
                'num_of_sale' => 0,
                'meta_title' => 'Cotton Printed Panjabi for Men - Ash',
                'meta_description' => 'The actual color of the physical product may slightly vary due to the deviation of lighting sources, photography or your device display settings. Delivery charges may vary as per the location, Product Size and Weight; we will notify before proceeding the delivery.',
                'meta_img' => '56',
                'pdf' => NULL,
                'slug' => 'cotton-printed-panjabi-for-men-ash-17638p-c4neV-GCbyp-MZyjv-kDg1Z-6DYx3-d60P8',
                'rating' => 0.0,
                'barcode' => NULL,
                'digital' => 0,
                'auction_product' => 0,
                'file_name' => NULL,
                'file_path' => NULL,
                'external_link' => NULL,
                'external_link_btn' => NULL,
                'wholesale_product' => 0,
                'created_at' => '2022-05-25 19:13:36',
                'updated_at' => '2022-08-06 15:38:36',
            ),
        ));
        
        
    }
}