<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UploadsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('uploads')->delete();
        
        \DB::table('uploads')->insert(array (
            0 => 
            array (
                'id' => 1,
                'file_original_name' => '3BwAd13a8eGT2Sq94aPUDcYpKzGHhiHPo0cduOfL',
                'file_name' => 'uploads/all/A3NcLr7A59De4Z5eTRnqChQLGn0MpssawRjcB1zA.jpg',
                'user_id' => 9,
                'file_size' => 307871,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:50',
                'updated_at' => '2022-05-25 12:05:50',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'file_original_name' => '6bV6QXVsxUA3dGXWFW0siab17b35qR9nntlieOtV',
                'file_name' => 'uploads/all/HoozpYqqyQswcWNnA91bFLG0OObDJ5UmAfK1iJEC.jpg',
                'user_id' => 9,
                'file_size' => 17263,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:50',
                'updated_at' => '2022-05-25 12:05:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'file_original_name' => '8QKkxiQD1KrUkpKt7nXI42AZTeeixt0dnpe88eHw',
                'file_name' => 'uploads/all/zwJsBeeupalv2iUkykfQjQJlk10MCBJG7uSHfOWC.jpg',
                'user_id' => 9,
                'file_size' => 62996,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:50',
                'updated_at' => '2022-05-25 12:05:50',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'file_original_name' => 'aEJt5qiP6DbW728b8jEl7meKciAGCSUbhCUgH2nF',
                'file_name' => 'uploads/all/hNOnDbZVgqfsLLi178Qqna3Z9ZBF6CAA0727j22C.jpg',
                'user_id' => 9,
                'file_size' => 40694,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:51',
                'updated_at' => '2022-05-25 12:05:51',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'file_original_name' => 'BvL8iDq4dO7yAjspt7W8gvSTTDhcQFFXO31gqTL2',
                'file_name' => 'uploads/all/8zgTqq80YM2pl2Kf1FSbj2wvLNtt3Xn8B97hHadM.jpg',
                'user_id' => 9,
                'file_size' => 30465,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:51',
                'updated_at' => '2022-05-25 12:05:51',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'file_original_name' => 'A7STWWrR6OZa5Hdi4MrINamiKeItSKOb3Zq2uOp5',
                'file_name' => 'uploads/all/dioWHSdEFEU50XdHPNeuxgz1ftedATd0PC33oQrG.jpg',
                'user_id' => 9,
                'file_size' => 69556,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:52',
                'updated_at' => '2022-05-25 12:05:52',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'file_original_name' => 'b93XHghfnu9mDs9tvW2dBChc7TZtHYHlYxrU9J1r',
                'file_name' => 'uploads/all/wkBWputDWjd13TAzcinKmeO09GP8OX7odAPSYNFU.jpg',
                'user_id' => 9,
                'file_size' => 62725,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:52',
                'updated_at' => '2022-05-25 12:05:52',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'file_original_name' => 'c4sgIs2rxvs4ERcM0Lh1tpsKOHD0rZa2K5zKS1sh',
                'file_name' => 'uploads/all/DtLqOEy2MFq6rppau7iRtbn6NAqJ9oOtWcRucu3x.jpg',
                'user_id' => 9,
                'file_size' => 80145,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:53',
                'updated_at' => '2022-05-25 12:05:53',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'file_original_name' => 'CRQe18Pkp4ap0chcCAHifCHVnIFMI0nNGAsPog1w',
                'file_name' => 'uploads/all/pGCpTAIXRCukjP4c2dKLrAwR5uHn4VBy2XstZXep.jpg',
                'user_id' => 9,
                'file_size' => 6834,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:53',
                'updated_at' => '2022-05-25 12:05:53',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'file_original_name' => 'cgWzwX2wQhefuJd4i0dVeaYma03Kpf5NK091sAH0',
                'file_name' => 'uploads/all/1C2oNeiIFHQiev6uj4u27Dug3CmFNcPt4KcxnWYC.jpg',
                'user_id' => 9,
                'file_size' => 45636,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:54',
                'updated_at' => '2022-05-25 12:05:54',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'file_original_name' => 'cWJgEMPP5v7Q2oYJMkAw7VojJ4kRPRISogsD8RuX',
                'file_name' => 'uploads/all/Rn6hkmR2FYjxhMNVQ2lS6nulzIOwNLBNikD9vW9g.jpg',
                'user_id' => 9,
                'file_size' => 50183,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:54',
                'updated_at' => '2022-05-25 12:05:54',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'file_original_name' => 'dRTiNmh0fY7OVuvtDNAy1kPqwb5f9FuPqByuSu9D',
                'file_name' => 'uploads/all/IDaaEFitTAv0d2bou9136x6E7jdVUTOEDNpx2l11.jpg',
                'user_id' => 9,
                'file_size' => 68107,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:54',
                'updated_at' => '2022-05-25 12:05:54',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'file_original_name' => 'gonYcFYQJ07JPn4mxA8XsYSLZowR9vGx9zt4yHj7',
                'file_name' => 'uploads/all/JawOE5MOT2WRgKc6MowKiUJFFzPQnv0lOabnwsI5.jpg',
                'user_id' => 9,
                'file_size' => 53212,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:55',
                'updated_at' => '2022-05-25 12:05:55',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'file_original_name' => 'ICKGSHUxICiJKBVHuUxbvCqC99azizwyHDwXVCno',
                'file_name' => 'uploads/all/ZyOx7TrCMTLjEmCPZdmKVdfJubO8F3bLTrpaAeCU.jpg',
                'user_id' => 9,
                'file_size' => 28431,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:55',
                'updated_at' => '2022-05-25 12:05:55',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'file_original_name' => 'haRauiltgb2iTgvQQZWWuDxYFksQAJc0boFz3bKH',
                'file_name' => 'uploads/all/JD1uOHFcyAvpEeFH9fcTqiXLHAcztMF7wGISYOiN.jpg',
                'user_id' => 9,
                'file_size' => 92539,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:56',
                'updated_at' => '2022-05-25 12:05:56',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'file_original_name' => 'dcJ2idzwy6ZHOjIWhIe0Pbtl3g05GNbAOuhfEMWt',
                'file_name' => 'uploads/all/veqvF3aNbKcugdlfH3hqipdGNgn4Pf9B0FbWHfZA.jpg',
                'user_id' => 9,
                'file_size' => 179573,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:56',
                'updated_at' => '2022-05-25 12:05:56',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'file_original_name' => 'JeyIwMPFA6FL3vHAo40wYlKP5pZuFJC5HXzATWZb',
                'file_name' => 'uploads/all/UvRKYmFKuZyhiy4rYd20UVNiI8CCFwfRfTVWqVjd.jpg',
                'user_id' => 9,
                'file_size' => 23726,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:57',
                'updated_at' => '2022-05-25 12:05:57',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'file_original_name' => 'IiW6jkCCLaj0QtxdLE7EBE3NBE8R4dmQTyOGiUYS',
                'file_name' => 'uploads/all/OdOQyqlDv0C8koM5itD1T2Wk1j4D2PCys5YQUD16.jpg',
                'user_id' => 9,
                'file_size' => 95321,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:57',
                'updated_at' => '2022-05-25 12:05:57',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'file_original_name' => 'JfzwYb0BrKsybPGUqbzykXVJnh8XOnzim3dfyO9f',
                'file_name' => 'uploads/all/rzCZ4JXXFjRlFkYCVtEBlF8NwUwfQATveQMK1m8X.jpg',
                'user_id' => 9,
                'file_size' => 49532,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:57',
                'updated_at' => '2022-05-25 12:05:57',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'file_original_name' => 'KqkKlGf97kTg8Y3u2oAQEuIdUrvkoLKmY6M0vz5U',
                'file_name' => 'uploads/all/A9BNnfejr0yKojRju5usaDp1GqtK3B00qX3eVZbp.webp',
                'user_id' => 9,
                'file_size' => 18054,
                'extension' => 'webp',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:58',
                'updated_at' => '2022-05-25 12:05:58',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'file_original_name' => 'Kbvq531IYwVmdzZhRJQtkZ9oZg5YzM6qPdakdPAY',
                'file_name' => 'uploads/all/6rPN135Ex7KO3fIcf2GH9zzL7Ey1HvXMUWkzPAsv.jpg',
                'user_id' => 9,
                'file_size' => 112220,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:59',
                'updated_at' => '2022-05-25 12:05:59',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'file_original_name' => 'M4HqYuSUBhoYKt57GWmrRBuNxC5EZIlY6GyiRYcE',
                'file_name' => 'uploads/all/KtTsXp1C9mJHd28s64E2zdczSBLzGRiBryMcWojQ.jpg',
                'user_id' => 9,
                'file_size' => 54404,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:05:59',
                'updated_at' => '2022-05-25 12:05:59',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'file_original_name' => 'iPPXDKldB6BKsXVtVR1IBSceu0bfFay5SguDUhh6',
                'file_name' => 'uploads/all/XebpD3DS82ke7ezYVUmKbGUCV8e5b59TPiDALrs5.jpg',
                'user_id' => 9,
                'file_size' => 219815,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:00',
                'updated_at' => '2022-05-25 12:06:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'file_original_name' => 'C20Xi8hTNmQ2biH4qGOK6xa3Cc2ohh7k7i2ilM2q',
                'file_name' => 'uploads/all/eCU7QO3KROmHIvL3VEy0oSqkVAAlgqcppsYOukkh.png',
                'user_id' => 9,
                'file_size' => 594923,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:00',
                'updated_at' => '2022-05-25 12:06:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'file_original_name' => 'KURJZR5vU4tzi8F1El9sGLLVjunjQlVllsd9pMkT',
                'file_name' => 'uploads/all/sXiIjEKbquLXwfGveuvndRmJCVTaHQ1GeLYjqhtJ.jpg',
                'user_id' => 9,
                'file_size' => 284597,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:01',
                'updated_at' => '2022-05-25 12:06:01',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'file_original_name' => 'pOEUPzZnBX8FA4VYPy3zJ2cLyptTy8qc3ND2CQ9E',
                'file_name' => 'uploads/all/rPsrazKO1da5IlfSmimFLYxSwYScdmT4jELPXnU5.png',
                'user_id' => 9,
                'file_size' => 132531,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:02',
                'updated_at' => '2022-05-25 12:06:02',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'file_original_name' => 'PPIMu4d4WhA339jb9OxhNTwmyYTUPUF0FWdGaVa2',
                'file_name' => 'uploads/all/TWAiwA6pTaHo6sEtRbMI8Nj71SXza1l3XHkRcAv1.jpg',
                'user_id' => 9,
                'file_size' => 88508,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:02',
                'updated_at' => '2022-05-25 12:06:02',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'file_original_name' => 'LGgSb5L3hOrUPAaBQ191c2eHDbPnrgMIpfYqeTiU',
                'file_name' => 'uploads/all/Z9cS39amxTYLHnW8JdfacLuuhbDgX6epipoJuguv.png',
                'user_id' => 9,
                'file_size' => 568848,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:03',
                'updated_at' => '2022-05-25 12:06:03',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'file_original_name' => 'Pvz52QAXIvdzz54SOMDqV0U5P3R1gOeJuvIXBq7Q',
                'file_name' => 'uploads/all/ST6dxLw3LlwMVswPvEXhYNXhUNxhqcnUAZ3ojAAK.jpg',
                'user_id' => 9,
                'file_size' => 62282,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:04',
                'updated_at' => '2022-05-25 12:06:04',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'file_original_name' => 'RK5hwJR7eRoxcc4ji2UT622Azc0mQQUQ4MtKRnKg',
                'file_name' => 'uploads/all/gkSgzUYaTqQpy2y3i246pV29dYjnbHXdTprJyynx.jpg',
                'user_id' => 9,
                'file_size' => 26355,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:04',
                'updated_at' => '2022-05-25 12:06:04',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
            'file_original_name' => 'mYNx7pFoZq0CxnlIpjtWifYtwONhIPccK0lLMFfN (1)',
                'file_name' => 'uploads/all/jx9TJ5SHftYv0s4dXP6AaY1LFCLrDpmWGN7XEvyE.png',
                'user_id' => 9,
                'file_size' => 566212,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:05',
                'updated_at' => '2022-05-25 12:06:05',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'file_original_name' => 'PWxQ211zxo8iTNVO0AujYfi18qGNKe6mv9msC1CI',
                'file_name' => 'uploads/all/xsE7NUjwh0OK7S1WdrRvrNjpF79YRs8jN0z6a3jH.jpg',
                'user_id' => 9,
                'file_size' => 134533,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:05',
                'updated_at' => '2022-05-25 12:06:05',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'file_original_name' => 'mYNx7pFoZq0CxnlIpjtWifYtwONhIPccK0lLMFfN',
                'file_name' => 'uploads/all/yar27IIHoz8RIpSW6q0VjipyltNzTMlqaXQzsIA2.png',
                'user_id' => 9,
                'file_size' => 566212,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:06',
                'updated_at' => '2022-05-25 12:06:06',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'file_original_name' => 'U5bYnBPgKwCSzXPovqBpV9m0fivcQ0ELA2hrYMPL',
                'file_name' => 'uploads/all/Ar596mIDxBEWP0Vewz7itVJ2TOMaSNe8pr1RyojT.webp',
                'user_id' => 9,
                'file_size' => 27572,
                'extension' => 'webp',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:06',
                'updated_at' => '2022-05-25 12:06:06',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'file_original_name' => 'TAvr0h0b2BdPsTPjtFhmMOe9v9wCpri60uE9waTU',
                'file_name' => 'uploads/all/BdYx6k7LO2bOTFBr6tEJrPciuQ6HTBuvZQzwlwgr.jpg',
                'user_id' => 9,
                'file_size' => 55025,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:07',
                'updated_at' => '2022-05-25 12:06:07',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'file_original_name' => 'uw7x2gD9b0WZN8ckd87CSBzg3VIWP4rQeiQZ5Sjn',
                'file_name' => 'uploads/all/aBiYa1uUZisecAJnXU75AwZhOjTAYDvXzwjAam91.webp',
                'user_id' => 9,
                'file_size' => 29104,
                'extension' => 'webp',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:07',
                'updated_at' => '2022-05-25 12:06:07',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'file_original_name' => 't0vlINQdKxLnm29D95YI0ASloi2znU8zCskT75VW',
                'file_name' => 'uploads/all/7GHCAxeC0LnAXNWkxLbdxWaaZ9X1HxUReD3Mm5qA.jpg',
                'user_id' => 9,
                'file_size' => 151651,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:08',
                'updated_at' => '2022-05-25 12:06:08',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'file_original_name' => 'VeUPcDCQKr3xicS5h4iGR9BdYpZG7QLSx7niZJ9e',
                'file_name' => 'uploads/all/a2OptYSObCL6PUklDSuNxIgzzxnQtbPXOgZLfGTV.jpg',
                'user_id' => 9,
                'file_size' => 39609,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:08',
                'updated_at' => '2022-05-25 12:06:08',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'file_original_name' => 'OJ4JzxN8nbZUMMU4LhzQWFkKcm7wVYBybHdsZ3jS',
                'file_name' => 'uploads/all/zncsIwLquKZaScJCceYEzsLfDpTjCiBt1HmPdFlo.png',
                'user_id' => 9,
                'file_size' => 690861,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:09',
                'updated_at' => '2022-05-25 12:06:09',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'file_original_name' => 'Vyg9rdubMHQuhTEAqWQYICxm54lvWfjCQP75Zaqk',
                'file_name' => 'uploads/all/6AWremGriGKz2jwJfLVBFDg5ZmwbscDMuarH9laT.jpg',
                'user_id' => 9,
                'file_size' => 42365,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:10',
                'updated_at' => '2022-05-25 12:06:10',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'file_original_name' => 'Xtu6Crf4CqoBhWrP97PlY7qkaN50y8NWRBow8LGs',
                'file_name' => 'uploads/all/9npMoxHIkQbvBWG0CrCN9W3B50zK0KgZW1fy7iVQ.jpg',
                'user_id' => 9,
                'file_size' => 21493,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:10',
                'updated_at' => '2022-05-25 12:06:10',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'file_original_name' => 'URzgidvTRUd7FZCO1gmyVShDqi1LeWrwYMTpiLQL',
                'file_name' => 'uploads/all/rk50NNRfEIk3wpAoeY6iTKNQaHCLpOGrsFN9h4sX.jpg',
                'user_id' => 9,
                'file_size' => 150598,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:11',
                'updated_at' => '2022-05-25 12:06:11',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'file_original_name' => 'VS6RRY9VCpkA0MxVuHcIsImVDr1Ss8NUscLMzmcH',
                'file_name' => 'uploads/all/Z9BhJVkHYotxHYScJhF6BF4sVM2E9XvQBOb3moqB.jpg',
                'user_id' => 9,
                'file_size' => 102854,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:11',
                'updated_at' => '2022-05-25 12:06:11',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'file_original_name' => 'wNNWj2dcdWzgyPwXN30UsUCPW1ug85J61FApPK7W',
                'file_name' => 'uploads/all/OB3u1Tq4M2UT8vwmaWyoKoHSjHmt9rxs3PXHiARS.jpg',
                'user_id' => 9,
                'file_size' => 74177,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:11',
                'updated_at' => '2022-05-25 12:06:11',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'file_original_name' => 'YWlmkn6q29OOrRsQLJyR3MUc9BlEQNOKs9b2ZYlk',
                'file_name' => 'uploads/all/1RLmBAP4YUnjSw77WyOsSW9cf8fWNu23sidSY6J4.jpg',
                'user_id' => 9,
                'file_size' => 31629,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:12',
                'updated_at' => '2022-05-25 12:06:12',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'file_original_name' => 'zDjfjZWxXeyz8oonAGMOlIRptgyMHaXVnviGAFYA',
                'file_name' => 'uploads/all/rWKOBnbPKebTZ2UeF7uaknkyfnzFSZptE9GvFABD.jpg',
                'user_id' => 9,
                'file_size' => 68043,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:13',
                'updated_at' => '2022-05-25 12:06:13',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'file_original_name' => 'ZL7bdw8IqBTnJnJDrcIUPfEDTxzwUqGFvAeghIEk',
                'file_name' => 'uploads/all/HoIAS9xy82GzFSf42sxzbaGv7ke1ZYjLeNdEQH3l.jpg',
                'user_id' => 9,
                'file_size' => 65182,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 12:06:14',
                'updated_at' => '2022-05-25 12:06:14',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'file_original_name' => 'pXoU38FkQ5cJylGUL9KtP6tVVg57SDklqarQHJXx',
                'file_name' => 'uploads/all/UwT03k1hrGbNbfHcxzAuU7gp2tXlqnWsKRL0vwCL.png',
                'user_id' => 9,
                'file_size' => 611986,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:29:25',
                'updated_at' => '2022-05-25 15:29:25',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'file_original_name' => 'S9MPLBSBXqHmkvbV0sJbJpSK39UrGSFjtWjbqhJG',
                'file_name' => 'uploads/all/uMHMvNdIahMuYOmvfgROoe0OgrFxiFZZff1RfCdi.jpg',
                'user_id' => 9,
                'file_size' => 25319,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:34:35',
                'updated_at' => '2022-05-25 15:34:35',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'file_original_name' => 'YNLExfT5BRgRlERL7Tlxm6PXG6qc6aVOwqUzR9Ro',
                'file_name' => 'uploads/all/tPYIMI3SwWEPOTYH5c8OB0Dq5wddxciKqriNqkR8.jpg',
                'user_id' => 9,
                'file_size' => 33742,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:34:36',
                'updated_at' => '2022-05-25 15:34:36',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'file_original_name' => '4rbwK9AkZiKJC9qkTkZEh6E73nYuVpmEPuLunSOz',
                'file_name' => 'uploads/all/HvAixdx2KcgwxhDLshYj2w2v11G0uh2YZchOBcLm.jpg',
                'user_id' => 9,
                'file_size' => 173631,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:40:15',
                'updated_at' => '2022-05-25 15:40:15',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'file_original_name' => 'ab21eSfW3djoN7jUVGfoO1RRMd6FoiKDFrEy3cc0',
                'file_name' => 'uploads/all/paoTrNti2EG8MItqgw8gHt0lQ2IuUENzsG4YkpDt.jpg',
                'user_id' => 9,
                'file_size' => 155952,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:40:16',
                'updated_at' => '2022-05-25 15:40:16',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'file_original_name' => 'PRCFLGevxGbn1NZarZgrrWeTmt9FvlCwYJ5apx8O',
                'file_name' => 'uploads/all/3DjzzO43PQ1xL6kR9eaVNhr2aez0IbZFs2Rpv150.jpg',
                'user_id' => 9,
                'file_size' => 52154,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:48:55',
                'updated_at' => '2022-05-25 15:48:55',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'file_original_name' => 'Pvz52QAXIvdzz54SOMDqV0U5P3R1gOeJuvIXBq7Q',
                'file_name' => 'uploads/all/8sGaWTwXY55hjUyLUl2WNdxYk1yivadTor5Jnpx8.jpg',
                'user_id' => 9,
                'file_size' => 62282,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:48:56',
                'updated_at' => '2022-05-25 15:48:56',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'file_original_name' => 'tWIGKTzdPOxsmSdfYuNpcDduZW5V5leTgU4FTpr0',
                'file_name' => 'uploads/all/havggOgeXHiZHROUiO5NLy53oaHBN2ZQQvuYTWf6.jpg',
                'user_id' => 9,
                'file_size' => 57726,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:48:56',
                'updated_at' => '2022-05-25 15:48:56',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'file_original_name' => 'WIEmblHQKTM7VoQ0CPUHh4zKVyd2hDj3sPIQFrmM',
                'file_name' => 'uploads/all/N6HxRlxq7rV8Iyf8NX0FKMg60WZT8Lzt0bX5nitA.jpg',
                'user_id' => 9,
                'file_size' => 77321,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:48:57',
                'updated_at' => '2022-05-25 15:48:57',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'file_original_name' => 'XBQq2RCrqAQRob5ABVYKWH07CKa0Bx330h8YNaDc',
                'file_name' => 'uploads/all/g5CchRYPfoswmbMCecVQmCCtdVAMTgxCmrjBiDEw.jpg',
                'user_id' => 9,
                'file_size' => 60134,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 15:48:57',
                'updated_at' => '2022-05-25 15:48:57',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'file_original_name' => '63zdwu6kDHsIxGIJhwYm8hNuh2XYuXB5KvxOtfR6',
                'file_name' => 'uploads/all/gGM6b5OXXuVa92I4G6VwT10jkloJg309VtD9cffU.jpg',
                'user_id' => 9,
                'file_size' => 4360,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:31',
                'updated_at' => '2022-05-25 18:45:31',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'file_original_name' => 'CVo1G2QVpVtSoZlmCvC0l4hL9WIiWLlTQf6XclMC',
                'file_name' => 'uploads/all/VMaMOvVBD3WIt86anQC0SiDhVp23wCvzZcAGieah.jpg',
                'user_id' => 9,
                'file_size' => 4253,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:32',
                'updated_at' => '2022-05-25 18:45:32',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'file_original_name' => 'ecb0DAeSHXtbC4Fn6WYz8MBpJuqVeJweFHpO5Tdv',
                'file_name' => 'uploads/all/t9RGIyuvXk5ygTA4qB9WRSSsK5q54iJMY5jyPQow.jpg',
                'user_id' => 9,
                'file_size' => 2654,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:32',
                'updated_at' => '2022-05-25 18:45:32',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'file_original_name' => 'EAB1zQHsBz4bs8Z4DSKmdqYVV2OReXMxiqp32hCk',
                'file_name' => 'uploads/all/Jev5Zs3YsSX6VeEv1UK5LxbAScYwiatwFUdfwGmk.jpg',
                'user_id' => 9,
                'file_size' => 3087,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:33',
                'updated_at' => '2022-05-25 18:45:33',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'file_original_name' => 'ED7vbI8nnpPeKv6LXGYsGMCOLKG5s5uWyedONBxj',
                'file_name' => 'uploads/all/emXZ9L6vPXPMWrbs9f5Qu4nom9teb7zjHukk5y6a.jpg',
                'user_id' => 9,
                'file_size' => 4626,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:33',
                'updated_at' => '2022-05-25 18:45:33',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'file_original_name' => 'FtaUU28Xx2DcVKgr2liBnteXtWNqacQLfZXZiI3V',
                'file_name' => 'uploads/all/NY3SsAvA4sEetD20Eq4EypiQJQ9yBBUDeWMmqxZT.jpg',
                'user_id' => 9,
                'file_size' => 3519,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:34',
                'updated_at' => '2022-05-25 18:45:34',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'file_original_name' => 'hOcd5BOA7MVZ4y4potvCzMypnVKospMJsPZb1aPU',
                'file_name' => 'uploads/all/J3TgcvEIzXaiYW246jXLTIeS9Sbwk1KoPe0LH7R2.jpg',
                'user_id' => 9,
                'file_size' => 2622,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:34',
                'updated_at' => '2022-05-25 18:45:34',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'file_original_name' => 'igAkXQNWqVIiTSwKVsoG9DmihosVVTL6vp94K6qf',
                'file_name' => 'uploads/all/gLGpPNy3QCUPK7Ea0JI4vwr4KQRRBaiFr384uvry.jpg',
                'user_id' => 9,
                'file_size' => 3535,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:34',
                'updated_at' => '2022-05-25 18:45:34',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'file_original_name' => 'p1cHVKZSlCy5VrGjQRcHQclukEoRhapNQQHXz522',
                'file_name' => 'uploads/all/c7f64txdhA5ysP3SLdO92gtM4RyFGN74wMeEBRbR.jpg',
                'user_id' => 9,
                'file_size' => 3123,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:34',
                'updated_at' => '2022-05-25 18:45:34',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'file_original_name' => 'psvYUjmOREXrnLNH4O3h9pC3btmXDsyh96vSPEtk',
                'file_name' => 'uploads/all/soQVHQ2RFxDmKtnjWtI8WSnkpeEduVHdoKlPXSyn.jpg',
                'user_id' => 9,
                'file_size' => 4595,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:35',
                'updated_at' => '2022-05-25 18:45:35',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'file_original_name' => 'rCfpiBkUtiOz8Ipakex02EA8uNYXGySvQWH9phRx',
                'file_name' => 'uploads/all/QvgyZ15Swri2w7cYd4luPtOuX3x7rugb4o2jKRDH.jpg',
                'user_id' => 9,
                'file_size' => 3198,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:35',
                'updated_at' => '2022-05-25 18:45:35',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'file_original_name' => 'rkIzWJlmmr3Ae5oJMwgHbFp3Kg9uinm5su2hmHoH',
                'file_name' => 'uploads/all/15EpbgEmQVKgqeHGGM8d6oWvT5xGCzf5OPhIHk8W.jpg',
                'user_id' => 9,
                'file_size' => 4296,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:36',
                'updated_at' => '2022-05-25 18:45:36',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'file_original_name' => 'wgls595fwicRmQzu4tdUa7O6o0bHSrvY5elkBhsV',
                'file_name' => 'uploads/all/WN0RIRmskSHUj4eCjrjMWsMGGqGRFqUuCMjOAHJe.jpg',
                'user_id' => 9,
                'file_size' => 3749,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 18:45:36',
                'updated_at' => '2022-05-25 18:45:36',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'file_original_name' => 'CCTDpXrbwXrHiomyiDR1WpWW3x5BLH9I7GygYLCF',
                'file_name' => 'uploads/all/wUOt0hpojlVvGZRbiRXjHUfcT8JXIG9aMzoHf8G5.jpg',
                'user_id' => 9,
                'file_size' => 84569,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:09:11',
                'updated_at' => '2022-05-25 19:09:11',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'file_original_name' => '8tNei93MW8KVmwvkC9R8h969IhRaNsxSR3SPnCdu',
                'file_name' => 'uploads/all/JOIHotAeyMagYbVlSU1PaLhHvvQkZL8EK6Gv5gpA.jpg',
                'user_id' => 9,
                'file_size' => 32990,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:12:27',
                'updated_at' => '2022-05-25 19:12:27',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'file_original_name' => 'gu5d0hkeamE43DQ6x5GZ4q3l5ImxSVxbpaqhqIOj',
                'file_name' => 'uploads/all/rhtHbBZeBWPNVs5PQJJeLCqIxDxUIdS9xhfzIoQ3.jpg',
                'user_id' => 9,
                'file_size' => 68507,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:12:27',
                'updated_at' => '2022-05-25 19:12:27',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'file_original_name' => 'rhujGH0Ry2DtkiVepeXRBXL0YVKsSXMHaYUfrT64',
                'file_name' => 'uploads/all/WUP5s0BkkKGjD3xDub6jmpQgV5YnH8mbFexzxsCk.jpg',
                'user_id' => 9,
                'file_size' => 83248,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:12:28',
                'updated_at' => '2022-05-25 19:12:28',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'file_original_name' => 'ffCcH1nI9BOqItMSdqF9VfGcVz6eQO5TrjAktvA6',
                'file_name' => 'uploads/all/k48maSuA6y0ZAFILCcry32CEN4Lz9IfNCc3J32Cr.jpg',
                'user_id' => 9,
                'file_size' => 353080,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:17:19',
                'updated_at' => '2022-05-25 19:17:19',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'file_original_name' => 'UeX1eB88MEMHlDQotkogrPKo3WEtkM5jF7llLl07',
                'file_name' => 'uploads/all/B4OGZk8IU4gVokEgSXAus0TkjyOsSnOrw1wlryJ0.jpg',
                'user_id' => 9,
                'file_size' => 384194,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-05-25 19:17:20',
                'updated_at' => '2022-05-25 19:17:20',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'file_original_name' => 'logo',
                'file_name' => 'uploads/all/kpzWPYala68Pi91lIo88MwSsA8nu5OvesaorURmh.png',
                'user_id' => 9,
                'file_size' => 149129,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:13:32',
                'updated_at' => '2022-06-29 18:13:32',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'file_original_name' => 'bkash',
                'file_name' => 'uploads/all/nHymw6UmuZ6XXKgAKfm1tW4TrqUIvH5KLIBncOT1.png',
                'user_id' => 9,
                'file_size' => 5567,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:53:54',
                'updated_at' => '2022-06-29 18:53:54',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'file_original_name' => 'bkash',
                'file_name' => 'uploads/all/A2dcsRcdA9R22xxDGiyHbbbLqNRZrVLMUkY9vguk.png',
                'user_id' => 9,
                'file_size' => 5567,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:12',
                'updated_at' => '2022-06-29 18:54:12',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'file_original_name' => 'authorizenet',
                'file_name' => 'uploads/all/azRaiUaHQqFhJxN3HJy4ezovatlLo450HUrBjPZW.png',
                'user_id' => 9,
                'file_size' => 5026,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:12',
                'updated_at' => '2022-06-29 18:54:12',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'file_original_name' => 'aamarpay',
                'file_name' => 'uploads/all/7SNPUjcqKHLEk6q3JTrYYA6Z3EFQiUvj9J3PiKQ3.png',
                'user_id' => 9,
                'file_size' => 16491,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:13',
                'updated_at' => '2022-06-29 18:54:13',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'file_original_name' => 'cod',
                'file_name' => 'uploads/all/CiELCYQMmarap3ss1PmuuaWHlDwqzu2jo3Ju78gf.png',
                'user_id' => 9,
                'file_size' => 27051,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:13',
                'updated_at' => '2022-06-29 18:54:13',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'file_original_name' => 'flutterwave',
                'file_name' => 'uploads/all/4o3snSCO8pks7qIp36HgM1eduXFNNFHJppQk8AcZ.png',
                'user_id' => 9,
                'file_size' => 36018,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:13',
                'updated_at' => '2022-06-29 18:54:13',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'file_original_name' => 'instamojo',
                'file_name' => 'uploads/all/LZCMpS490M1LKc8Ias0B1y2NaT7MM2rfRO3amgON.png',
                'user_id' => 9,
                'file_size' => 23408,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:14',
                'updated_at' => '2022-06-29 18:54:14',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'file_original_name' => 'iyzico',
                'file_name' => 'uploads/all/aY73j8QXgMeoO0ilxhX0ua1b9qLh7HJABMknzSNT.png',
                'user_id' => 9,
                'file_size' => 13918,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:14',
                'updated_at' => '2022-06-29 18:54:14',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'file_original_name' => 'mpesa',
                'file_name' => 'uploads/all/KwQ7emGqya9mSeTlLqWeWZ4VgUW8Ls3ADkOSwO8z.png',
                'user_id' => 9,
                'file_size' => 25277,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:15',
                'updated_at' => '2022-06-29 18:54:15',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'file_original_name' => 'nagad',
                'file_name' => 'uploads/all/TWgr4uB5RFQMrMk5erGkhtWSLL9i4hj6LPcU0Zhn.png',
                'user_id' => 9,
                'file_size' => 5167,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:15',
                'updated_at' => '2022-06-29 18:54:15',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'file_original_name' => 'mercadopago',
                'file_name' => 'uploads/all/HapuS2ENln2ARsTWngAHSLtdYCAGwELS0TOKarSj.png',
                'user_id' => 9,
                'file_size' => 45827,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:15',
                'updated_at' => '2022-06-29 18:54:15',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'file_original_name' => 'ngenius',
                'file_name' => 'uploads/all/rQvN4FeQKch4E8CpJmGGLgosjsWN8mpovbRk26KE.png',
                'user_id' => 9,
                'file_size' => 24750,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:16',
                'updated_at' => '2022-06-29 18:54:16',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'file_original_name' => 'payfast',
                'file_name' => 'uploads/all/EN6ntcsSelow7AhRA2yLfTBy6QWtaq0BQ4jpey4y.png',
                'user_id' => 9,
                'file_size' => 15616,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:16',
                'updated_at' => '2022-06-29 18:54:16',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'file_original_name' => 'payhere',
                'file_name' => 'uploads/all/gMrNAMOWllxZaEbSk2wAp1KN82vv41flDJG8mrrp.png',
                'user_id' => 9,
                'file_size' => 28600,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:16',
                'updated_at' => '2022-06-29 18:54:16',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'file_original_name' => 'payku',
                'file_name' => 'uploads/all/ApxBiUSsZ57E0WcMOCYRcs0FrR1pXXRYrrVX39kO.png',
                'user_id' => 9,
                'file_size' => 32737,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:17',
                'updated_at' => '2022-06-29 18:54:17',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'file_original_name' => 'paypal',
                'file_name' => 'uploads/all/BGHAGtuwdiIXvOqX79GkGUcCzG4V04u24vodHYhP.png',
                'user_id' => 9,
                'file_size' => 24762,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:17',
                'updated_at' => '2022-06-29 18:54:17',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'file_original_name' => 'paytm',
                'file_name' => 'uploads/all/SsmRCMD1butJCUHoWeFCmg0ALwFeknX99x2sFKbL.png',
                'user_id' => 9,
                'file_size' => 8820,
                'extension' => 'jpg',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:17',
                'updated_at' => '2022-06-29 18:54:17',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'file_original_name' => 'paystack',
                'file_name' => 'uploads/all/bhkfSjL2mq9ZuAxWH3KD7MSejUVr4HrQxV6YQ5h3.png',
                'user_id' => 9,
                'file_size' => 38467,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:18',
                'updated_at' => '2022-06-29 18:54:18',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'file_original_name' => 'proxypay',
                'file_name' => 'uploads/all/AsKpaxttHJSeTJNTHmfF78vXNs1S3Gtom5Jdpllw.jpg',
                'user_id' => 9,
                'file_size' => 9234,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:18',
                'updated_at' => '2022-06-29 18:54:18',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'file_original_name' => 'payumoney',
                'file_name' => 'uploads/all/cdFi6qmmSJfcENpRLt5DtuzPdlkKstip4vBDDOJ2.png',
                'user_id' => 9,
                'file_size' => 3338,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:19',
                'updated_at' => '2022-06-29 18:54:19',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'file_original_name' => 'rave_payment',
                'file_name' => 'uploads/all/FWnE0uZPTiEY6a3IUdDk2Zj4NxEL23XOFJCrkwEF.png',
                'user_id' => 9,
                'file_size' => 5592,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:19',
                'updated_at' => '2022-06-30 03:54:33',
                'deleted_at' => '2022-06-30 03:54:33',
            ),
            98 => 
            array (
                'id' => 99,
                'file_original_name' => 'rozarpay',
                'file_name' => 'uploads/all/mX62AWau4WEuxfNAlDSfDswzcvwnsJEEJrBDKjd8.png',
                'user_id' => 9,
                'file_size' => 28715,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:19',
                'updated_at' => '2022-06-29 18:54:19',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'file_original_name' => 'sslcommerz',
                'file_name' => 'uploads/all/1Z2kOvYG6F2Gl94AphQ0mkNeIre46PsyuTIeZXZB.png',
                'user_id' => 9,
                'file_size' => 23974,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:20',
                'updated_at' => '2022-06-29 18:54:20',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'file_original_name' => 'stripe',
                'file_name' => 'uploads/all/T6hqFqRzhfru9o2yppmqzQyj826PmfV8tkgsBkl9.png',
                'user_id' => 9,
                'file_size' => 23710,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:20',
                'updated_at' => '2022-06-29 18:54:20',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'file_original_name' => 'sslcommerz-foo',
                'file_name' => 'uploads/all/G40TjrjeBULDwbmLleqFFFYZwfpKnwgWCuGEhm9T.png',
                'user_id' => 9,
                'file_size' => 58311,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:20',
                'updated_at' => '2022-06-29 18:54:20',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'file_original_name' => 'toyyibpay',
                'file_name' => 'uploads/all/dtc7rK1rM7HxYa4OES0IHtIis4GXQtAQHmRoqfzq.png',
                'user_id' => 9,
                'file_size' => 14678,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:21',
                'updated_at' => '2022-06-29 18:54:21',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'file_original_name' => 'twocheckout',
                'file_name' => 'uploads/all/9MxRHNMnTu4R9ilozFBWSeGo3e0DSZvsULsbblSE.png',
                'user_id' => 9,
                'file_size' => 9793,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:21',
                'updated_at' => '2022-06-29 18:54:21',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'file_original_name' => 'save',
                'file_name' => 'uploads/all/2Zfyp69f4GLtUFQVR29ERPqGi5fKcsxqckV1kFi3.png',
                'user_id' => 9,
                'file_size' => 95634,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:22',
                'updated_at' => '2022-06-29 18:54:22',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'file_original_name' => 'wallet',
                'file_name' => 'uploads/all/ejDKCzS6MyoN5x8UwHOR7Qmd3Sr01xAgutEO4ArV.png',
                'user_id' => 9,
                'file_size' => 32218,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:22',
                'updated_at' => '2022-06-29 18:54:22',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'file_original_name' => 'vogue',
                'file_name' => 'uploads/all/skLIUmXw13HGo7olT4Nk7dfjsA5cqZlRTWpewMny.png',
                'user_id' => 9,
                'file_size' => 106062,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 18:54:23',
                'updated_at' => '2022-06-29 18:54:23',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'file_original_name' => 'icon',
                'file_name' => 'uploads/all/AvVpGfs6ApcddillqQHZsV5CZaalfS4klvoCceam.png',
                'user_id' => 9,
                'file_size' => 1594,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-06-29 21:27:58',
                'updated_at' => '2022-06-29 21:27:58',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'file_original_name' => 'SvMCZA1y16EK2469WNCYf4sGTGQLJ5KBosBmPD7W',
                'file_name' => 'uploads/all/iZTocQ3dfa8AwzKcH1uP3ua04mkUlM3G9OgThfIQ.png',
                'user_id' => 9,
                'file_size' => 336975,
                'extension' => 'png',
                'type' => 'image',
                'external_link' => NULL,
                'created_at' => '2022-07-27 05:41:56',
                'updated_at' => '2022-07-27 05:41:56',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}